### PR TITLE
Travis: Update package-lock.json

### PR DESCRIPTION
**Pull request by MattiasLevlin**
This PR is similar to the previous https://github.com/CSCfi/etsin-finder/pull/586

Travis deployment fails ( https://travis-ci.com/github/CSCfi/etsin-finder/jobs/462225761 ) ... due to differences in package-lock.json, related to recent updates to package.json:
- CSCFAIRMETA-28: https://github.com/CSCfi/etsin-finder/pull/654
- CSCFAIRMETA-805: https://github.com/CSCfi/etsin-finder/commit/833e39bad0ef9da250c44dcb318f6e1efc1855f2
- CSCFAIRMETA-831: https://github.com/CSCfi/etsin-finder/pull/653/

What was done:
- In local env, `git checkout test && git pull`
- In local env, `npm prune && npm install --only=production`
- Result: this PR

### CODE REVIEW

**Review by tahme — APPROVED** [review]

**Comment by kasperkeinanen** [comment]
Why `npm install --only=production`? This will mess up the package-lock.json for local development since the dev dependencies are needed there and lead to someone having to change it. Have there been any direct changes to any code in the test environment?

**Comment by MattiasLevlin** [comment]
> Why `npm install --only=production`? This will mess up the package-lock.json for local development since the dev dependencies are needed there and lead to someone having to change it. Have there been any direct changes to any code in the test environment?

Because that command is what Travis runs for test (and stable) here:
https://github.com/CSCfi/etsin-ops/blob/8a34e974596042d4d86091f4010835fbc898d54c/ansible/roles/frontend/tasks/main.yml#L45

After running that on the server, the package-lock.json should be identical to what's found in the repository, because the etsin-ops ansible code will thereafter try to do git pull in the task:
`deploy_webservers : Pull latest data from web app project remote repo branch test`

Currently, these new lines in this PR are found on etsin-web-test (because Travis has executed the task npm install --only=production), but these lines are not found on the remote repo branch test. Deployments will fail when Travis tries to do git pull through Ansible, because the package-lock.json on is not identical to what is found in the repository.

There has not been any direct or actual code changes in test.

**Comment by MattiasLevlin** [comment]
The failed task can be seen here
https://travis-ci.com/github/CSCfi/etsin-finder/jobs/462225761

fatal: [etsin-web-test-1]: FAILED! => {"before": "5eedbbcd5f539145e02b18cb4e49dfe2597b4197", "changed": false, "msg": "Local modifications exist in repository (force=no)."}

... and running `git diff` on the server will display the differing lines in package-lock.json

**Comment by MattiasLevlin** [comment]
The dev dependencies could be evaluated in a separate task/PR, though I think the first step should be to fix Travis so that any PRs merged to test will get deployed.

**Comment by kasperkeinanen** [comment]
Well my concern is that the package-lock.json should not be determined by what is built on the server but always be the one gotten from the remote, otherwise the environment on the server can have other dependencies than tested locally. And changing the lock file to fit the test environment can effect the other environments. But if this resolves the issue, try it.

**Comment by MattiasLevlin** [comment]
> Well my concern is that the package-lock.json should not be determined by what is built on the server but always be the one gotten from the remote, otherwise the environment on the server can have other dependencies than tested locally. And changing the lock file to fit the test environment can effect the other environments. But if this resolves the issue, try it.

That is a good point. It would be useful to also test functionality with non-local dependencies, though I guess for now this is what can be done manually when the code is deployed to test or stable (or even demo). Non-local dependencies could also be tested locally by running the app with similar npm options as to how its run in test or other non-local environments.

As I understand it, as Etsin-Qvain is implemented currently it will always have different dependencies in local_development build compared to a non-local builds, because the list of dev dependencies differ from the list of dependencies.

That `git pull` operation in Ansible functions as an additional step to verify that what is found on the server exactly matches the latest release/state of the GitHub repository. This verifies that, after deployments, the deployed code is identical on `test`, `stable`, and finally (most importantly) `master` a.k.a. production.

**Comment by MattiasLevlin** [comment]
Successfully deployed
https://travis-ci.com/github/CSCfi/etsin-finder/jobs/462365742

**Comment by MattiasLevlin** [comment]
To investigate: possibility of building the application outside the target environment and just deploying the code to the server.

**Pull request merged**
